### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by Caroline-Brnd** [azetoy/C-Pattern-Matching#1]
Bonjour !

Voulez-vous que je modifies votre readme pour expliquer votre projet ? Cela peut être bien, par exemple, si quelqu'un veut savoir à quoi correspond votre projets ! 

Meilleures salutations

**Comment by azetoy** [comment]
Ça me serais d'une grande aide je vous donnes les droit sur ce projet pour que vous puissiez faire les modifications nécessaires :)
